project:
  type: website
  output-dir: docs
  
website: 
  title: "FMD Preclinical Spread"
  navbar:
    left:
      - href: data_preparation.qmd
        text: Data Preparation
      - href: infections.qmd
        text: Outbreak Magnitude
      - href: duration.qmd
        text: Epidemic Duration
      - href: spread.qmd
        text: Transmission Metrics
      - href: outbreak_maps.qmd
        text: Outbreak Maps
    right:
      - href: https://geoepi.github.io/
        text: GeoEpi
      - icon: github
        href: https://github.com/geoepi/fmd-preclinical-spread
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

