project:
  type: website
  output-dir: docs
  
website: 
  title: "FMD Preclinical Spread"
  navbar:
    left:
      - href: duration.qmd
        text: Outbreak Duration
      - href: Re.qmd
        text: Effective Reproduction (Re)
      - href: velocity.qmd
        text: Epidemic Velocity
      - href: spread.qmd
        text: Geographic Extent
    right:
      - href: https://geoepi.github.io/
        text: GeoEpi
      - icon: github
        href: https://github.com/geoepi/fmd-preclinical-spread
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: lux
    toc: true
    
editor: source

