---
title: "Overview"
description: ""
format:
  html: 
    df-print: kable
    code-fold: true
    code-summary: "Code"
    code-overflow: wrap
    toc-title: Page Contents
    toc: true
    toc-depth: 2
    toc-location: right
    number-sections: false
    html-math-method: katex
    smooth-scroll: true
editor: source
editor_options: 
  chunk_output_type: console
---

```{=html}
<style type="text/css">

body, td {
   font-size: 13pt;
}
code.r{
  font-size: 9pt;
}
pre {
  font-size: 11pt
}
</style>
```

::: {.callout-important icon="true"}
#### Under Peer Review

This site provides supporting information for the manuscript:

**Modeling Incubation Phase Transmission of Foot-and-Mouth Disease Virus in Cattle** [*in review*]

Scharzenberger, Humphreys, Rigney, Freifeld, Stenfeldt, and Arzt

*This work is currently under peer review and is subject to change.*
:::

## About
This site provides a demonstrative workflow of the statistical methods used to analyze InterSpread Plus outputs from a FMDV preclinical transmission model in United States cattle. Simulations were run for multiple geographic regions. Figures for the Western U.S. are included in the main text of the manuscript. Tables and figures for the Eastern U.S. and Central U.S. region scenarios are included on this site as supplemental materials.

## Navigation
The menu at right can be used to navigate through major sections on a webpage. Links across the top of the page will direct to specific analyses. Throughout this website, panels are used to display results across regional scenarios.

::: {.callout-tip icon=true}
#### View Comparisons

Select the tabs to view comparisons between regional scenarios.

:::

::: panel-tabset
## Central U.S.
FMDV-spread was simulated throughout the Central U.S. region.

## Eastern U.S.
FMDV-spread was simulated throughout the Eastern U.S. region.

:::
